enum StatusType {
    SUCCESS,
    HARD_FAIL_PRINTER_TYPE,
    HARD_FAIL_PROFILE_VERSION,
    HARD_FAIL_FILAMENT_TYPE,
    SOFT_FAIL_HIGH_INFILL,
    SOFT_FAIL_SUPPORT_TYPE,
    SOFT_FAIL_HUGE_PRINT
}
