// This file is automatically generated by tool/GenerateAst
package crisp;

import java.util.List;

abstract class Expr {
    interface Visitor<R> {
        R visitCommandExpr(Command expr);
        R visitParamExpr(Param expr);
    }
    static class Command extends Expr{
        Command(Token command, Expr param) {
            this.command = command;
            this.param = param;
        }

        @Override
        <R> R accept(Visitor<R> visitor) {
            return visitor.visitCommandExpr(this);
        }

        final Token command;
        final Expr param;
    }

    static class Param extends Expr{
        Param(Token param) {
            this.param = param;
        }

        @Override
        <R> R accept(Visitor<R> visitor) {
            return visitor.visitParamExpr(this);
        }

        final Token param;
    }

    abstract <R> R accept(Visitor<R> visitor);
}
