package crisp;

import java.util.HashMap;

// This ConsumerModule converts tokens generated from the Prusa autogenerated
// comments of the form key = value; into a very simple grammar which is currently
// implemented as a no-frills dictionary.
class PrusaCommentConsumer extends ConsumerModule<HashMap<String, Token>> {

    PrusaCommentConsumer(LazyParser p) {
        super(p);
        data = new HashMap<String, Token>();
        // The data structure a ConsumerModule uses can be this simple for this
        // simple of a grammar
    }

    void examineToken(Token t) {
        if (t.type instanceof PrusaCommentToken) {
            // we don't care about any other types

            if (check(PrusaCommentToken.KEY)) {
                advance();
                if (check(PrusaCommentToken.VALUE))
                    // System.out.println("About to add config " + t + " " + peek());
                    data.put(t.strValue, peek());
                }
            }
    }

}
